; ============================================================
; Parqueadero Inteligente - Firmware ESP32
; PlatformIO Project Configuration File
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Velocidad del monitor serial
monitor_speed = 115200

; Librerías que usaremos más adelante (se descargan automático)
lib_deps =
    
    knolleary/PubSubClient @ ^2.8

; Si el puerto no se detecta solo, descomenta y ajusta:
; upload_port = COM5
; monitor_port = COM5

build_flags =
    -D CORE_DEBUG_LEVEL=3
